version: "3"
services: 
    api:
        build: .
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        command: ["sh", "-c", "alembic upgrade head ; uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=admin
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=60
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=fastapi
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi"]
            interval: 5s
            timeout: 10s
            retries: 5
        volumes:
            - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db: 